### ISSUE TITLE
auth, nonce, salt all the same? 

### ISSUE THREAD

**Issue by frame45** [do-community/ansible-playbooks#2]
I just ran this playbook on a digital ocean droplet as a test WP install. the `wp-config.php` file has the same hash for all of the entries. Is this a security issue? I ask because [https://api.wordpress.org/secret-key/1.1/salt/](https://api.wordpress.org/secret-key/1.1/salt/) creates unique hashes for each entry. Just curious, thanks.
`define( 'AUTH_KEY',         'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'SECURE_AUTH_KEY',  'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'LOGGED_IN_KEY',    'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'NONCE_KEY',        'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'AUTH_SALT',        'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'SECURE_AUTH_SALT', 'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'LOGGED_IN_SALT',   'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
define( 'NONCE_SALT',       'fa95c7b309e54ea30316c3b16db4a9f5518feae60efa5ae5ec43334773a89198' );
`

**Comment by erikaheidi** [comment]
Hello @frame45 ! Thank you for finding this. Indeed, these should be different tokens. I will be working on this issue asap.

**Comment by erikaheidi** [comment]
It is fixed in the master branch! :+1: Thanks again for surfacing the problem.

**Comment by frame45** [comment]
Yay, thanks, these playbooks have been very helpful for me.
